### ISSUE TITLE
关于将数据转换成图像的代码使用

### ISSUE THREAD

**Issue by wongsihan** [ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark#2]
您好，非常感谢您将代码开源。
我在使用过程中遇到一个问题，在调用cnn_2d为测试模型时，需要输入的数据是2d，否则会报错：
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 1, 3, 3], but got 3-dimensional input of size [64, 1, 512] instead
但是我没有找到如何调整输入为2d的代码和对应做法，请问该如何解决呢？

**Comment by ZhaoZhibin** [comment]
当你用2D的模型时，你需要配合2D的输入。如果你是自己的数据集，则需要重新写一个dataset，可以参考CWRUSTFT，CWRUCWT和CWRUSlice，这三个都是二维输入。如果你是用的这里面的数据，那就需要配合二维的输入，即CWRUSTFT，CWRUCWT和CWRUSlice。

**Comment by ZhaoZhibin** [comment]
> 您好，非常感谢您将代码开源。
> 我在使用过程中遇到一个问题，在调用cnn_2d为测试模型时，需要输入的数据是2d，否则会报错：
> RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 1, 3, 3], but got 3-dimensional input of size [64, 1, 512] instead
> 但是我没有找到如何调整输入为2d的代码和对应做法，请问该如何解决呢？

当你用2D的模型时，你需要配合2D的输入。如果你是自己的数据集，则需要重新写一个dataset，可以参考CWRUSTFT，CWRUCWT和CWRUSlice，这三个都是二维输入。如果你是用的这里面的数据，那就需要配合二维的输入，即CWRUSTFT，CWRUCWT和CWRUSlice。

**Comment by wongsihan** [comment]
> > 您好，非常感谢您将代码开源。
> > 我在使用过程中遇到一个问题，在调用cnn_2d为测试模型时，需要输入的数据是2d，否则会报错：
> > RuntimeError: Expected 4-dimensional input for 4-dimensional weight [16, 1, 3, 3], but got 3-dimensional input of size [64, 1, 512] instead
> > 但是我没有找到如何调整输入为2d的代码和对应做法，请问该如何解决呢？
> 
> 当你用2D的模型时，你需要配合2D的输入。如果你是自己的数据集，则需要重新写一个dataset，可以参考CWRUSTFT，CWRUCWT和CWRUSlice，这三个都是二维输入。如果你是用的这里面的数据，那就需要配合二维的输入，即CWRUSTFT，CWRUCWT和CWRUSlice。

收到！我去调试看看，感谢您的回复，祝您科研顺利。
