### ISSUE TITLE
Possible error in CWRUFFT.py

### ISSUE THREAD

**Issue by Lucashsmello** [ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark#7]
Hi. The file CNN_Datasets/R_NA/datasets/CWRUFFT.py, at line [105](https://github.com/ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark/blob/11e838ecaf16cabe5fbf747fb6ec7996c95d4170/CNN_Datasets/R_NA/datasets/CWRUFFT.py#L105), adds noise to the training dataset, despite being used for a classification task. Is that correct?

**Comment by ZhaoZhibin** [comment]
In the paper, we also discussed the data augmentation, and thus RandomAddGaussian() means randomly adding Gaussian noise in each training sample and is one kind of the data augmentation method. Data augmentation is a common step in image classification, which can sometimes enhance the generalization ability of the model. Thus, we discussed it.

**Comment by ZhaoZhibin** [comment]
> Hi. The file CNN_Datasets/R_NA/datasets/CWRUFFT.py, at line [105](https://github.com/ZhaoZhibin/DL-based-Intelligent-Diagnosis-Benchmark/blob/11e838ecaf16cabe5fbf747fb6ec7996c95d4170/CNN_Datasets/R_NA/datasets/CWRUFFT.py#L105), adds noise to the training dataset, despite being used for a classification task. Is that correct?

In the paper, we also discussed the data augmentation, and thus RandomAddGaussian() means randomly adding Gaussian noise in each training sample and is one kind of the data augmentation method. Data augmentation is a common step in image classification, which can sometimes enhance the generalization ability of the model. Thus, we discussed it.

**Comment by Lucashsmello** [comment]
Thanks for your response. That is right.
However, shouldn't datasets on R_NA folder be free of data augmentation?

**Comment by ZhaoZhibin** [comment]
> Thanks for your response. That is right. However, shouldn't datasets on R_NA folder be free of data augmentation?

Yes, you are right! We have made a mistake when cleaning up our codes. I have modified this error, which happens in both AE and CNN

**Comment by Lucashsmello** [comment]
Nice! Many thanks. This seems to happen to other datasets in CNN_Datasets/R_NA folder too:
- CWRUCWT.py
- JNUCWT.py
- MFPTCWT.py
- PUCWT.py
- PU.py
- SEUCWT.py
- UoCCWT.py
- XJTUCWT.py
They all use RandomScaler and RandomCrop.

**Comment by ZhaoZhibin** [comment]
> Nice! Many thanks. This seems to happen to other datasets in CNN_Datasets/R_NA folder too:
> 
> * CWRUCWT.py
> * JNUCWT.py
> * MFPTCWT.py
> * PUCWT.py
> * PU.py
> * SEUCWT.py
> * UoCCWT.py
> * XJTUCWT.py
>   They all use RandomScaler and RandomCrop.

Thanks very much!

**Comment by Lucashsmello** [comment]
Resolved.
